language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

services:
    - redis-server

before_install:
    - "cpanm -q -n Dist::Zilla::PluginBundle::Author::CHIM"

install:
    - "dzil authordeps | xargs cpanm -q -n && dzil listdeps | xargs cpanm -q -n"
    - "export TRAVIS_CI_ORG_BUILD=1"
    - "echo Travis-CI.org [$TRAVIS_CI_ORG_BUILD]"

script:
    - "dzil test --release"
